<?php

namespace Digitalcloud\MultilingualNova;

use Laravel\Nova\Fields\Field;

class Multilingual extends Field
{
    /**
     * The field's component.
     *
     * @var string
     */
    public $component = 'multilingual-nova';

    public $showOnCreation = false;
    public $showOnUpdate = false;

    protected function resolveAttribute($resource, $attribute)
    {
//        dd(parent::resolveAttribute($resource, $attribute));
        return [
            'id' => $resource->id,
            'locales' => [
                [
                    'label' => 'EN',
                    'value' => 'en',
                    'translated' => true,
                ],
                [
                    'label' => 'AR',
                    'value' => 'ar',
                    'translated' => false,
                ]
            ]
        ];
//        return parent::resolveAttribute($resource, $attribute); // TODO: Change the autogenerated stub
    }
}
